import type { CatalogRoute } from './catalog-records'

export const cubeCatalog: CatalogRoute[] = [
  {
    id: 'cube-a-clockwork-orange',
    sourceId: 'mp-route-107004798',
    sourceName: 'A Clockwork Orange',
    name: 'A Clockwork Orange',
    routeUrl:
      'https://www.mountainproject.com/route/107004798/a-clockwork-orange',
    grade: 'V12',
    fontGrade: '8A+',
    gradeValue: 12,
    risk: 'PG13',
  },
  {
    id: 'cube-big-love',
    sourceId: 'mp-route-112430327',
    sourceName: 'Big Love',
    name: 'Big Love',
    routeUrl: 'https://www.mountainproject.com/route/112430327/big-love',
    grade: 'V4',
    fontGrade: '6B',
    gradeValue: 4,
    risk: 'R',
  },
  {
    id: 'fear-of-a-black-hat',
    sourceId: 'mp-black-hat',
    sourceName: 'Fear of a Black Hat',
    name: 'Fear of a Black Hat',
    routeUrl:
      'https://www.mountainproject.com/route/107004045/fear-of-a-black-hat',
    grade: 'V9',
    fontGrade: '7C',
    gradeValue: 9,
    risk: 'PG13',
  },
  {
    id: 'cube-full-regulation',
    sourceId: 'mp-route-116693657',
    sourceName: 'Full Regulation',
    name: 'Full Regulation',
    routeUrl: 'https://www.mountainproject.com/route/116693657/full-regulation',
    grade: 'V3',
    fontGrade: '6A',
    gradeValue: 3,
    risk: 'R',
  },
  {
    id: 'cube-marriage',
    sourceId: 'mp-route-124045669',
    sourceName: 'Marriage',
    name: 'Marriage',
    routeUrl: 'https://www.mountainproject.com/route/124045669/marriage',
    grade: 'V6+',
    fontGrade: '7A',
    gradeValue: 6,
    risk: 'R',
  },
  {
    id: 'cube-marriage-sit',
    sourceId: 'mp-route-124045709',
    sourceName: 'Marriage Sit',
    name: 'Marriage Sit',
    routeUrl: 'https://www.mountainproject.com/route/124045709/marriage-sit',
    grade: 'V7-',
    fontGrade: '7A+',
    gradeValue: 7,
    risk: 'R',
  },
  {
    id: 'cube-martinets-rails',
    sourceId: 'mp-route-113857995',
    sourceName: "Martinet's Rails",
    name: "Martinet's Rails",
    routeUrl: 'https://www.mountainproject.com/route/113857995/martinets-rails',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
    risk: 'PG13',
  },
  {
    id: 'perfect-poser',
    sourceId: 'mp-perfect-poser',
    sourceName: 'Perfect Poser',
    name: 'Perfect Poser',
    routeUrl: 'https://www.mountainproject.com/route/105959433/perfect-poser',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
    risk: 'R',
  },
  {
    id: 'cube-total-devastation',
    sourceId: 'mp-route-111470042',
    sourceName: 'Total Devastation',
    name: 'Total Devastation',
    routeUrl:
      'https://www.mountainproject.com/route/111470042/total-devastation',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
    risk: 'R',
  },
  {
    id: 'cube-total-devastation-direct',
    sourceId: 'mp-route-121616668',
    sourceName: 'Total Devastation Direct',
    name: 'Total Devastation Direct',
    routeUrl:
      'https://www.mountainproject.com/route/121616668/total-devastation-direct',
    grade: 'V8',
    fontGrade: '7B',
    gradeValue: 8,
    risk: 'R',
  },
  {
    id: 'cube-total-devastation-left',
    sourceId: 'mp-route-124045533',
    sourceName: 'Total Devastation Left',
    name: 'Total Devastation Left',
    routeUrl:
      'https://www.mountainproject.com/route/124045533/total-devastation-left',
    grade: 'V4',
    fontGrade: '6B',
    gradeValue: 4,
    risk: 'R',
  },
  {
    id: 'west-face-left',
    sourceId: 'mp-west-face-left',
    sourceName: 'West Face Left',
    name: 'West Face Left',
    routeUrl: 'https://www.mountainproject.com/route/107004813/west-face-left',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
    risk: 'PG13',
  },
]
