import type { CatalogRoute } from './catalog-records'

export const monkeyCatalog: CatalogRoute[] = [
  {
    id: 'monkey-blunt-arete',
    sourceId: 'mp-route-114126068',
    sourceName: 'Blunt Arete',
    name: 'Blunt Arete',
    routeUrl: 'https://www.mountainproject.com/route/114126068/blunt-arete',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
  },
  {
    id: 'monkey-center-face',
    sourceId: 'mp-route-108731189',
    sourceName: 'Center Face',
    name: 'Center Face',
    routeUrl: 'https://www.mountainproject.com/route/108731189/center-face',
    grade: 'V2-3',
    fontGrade: '5+',
    gradeValue: 2,
    gradeMaxValue: 3,
  },
  {
    id: 'monkey-curious-george',
    sourceId: 'mp-route-114000041',
    sourceName: 'Curious George',
    name: 'Curious George',
    routeUrl: 'https://www.mountainproject.com/route/114000041/curious-george',
    grade: 'V3-',
    fontGrade: '6A',
    gradeValue: 3,
  },
  {
    id: 'monkey-darwin-award',
    sourceId: 'mp-route-107513950',
    sourceName: 'Darwin Award',
    name: 'Darwin Award',
    routeUrl: 'https://www.mountainproject.com/route/107513950/darwin-award',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
  },
  {
    id: 'monkey-glory-hole',
    sourceId: 'mp-route-107838637',
    sourceName: 'Glory Hole',
    name: 'Glory Hole',
    routeUrl: 'https://www.mountainproject.com/route/107838637/glory-hole',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
  },
  {
    id: 'hyperglide',
    sourceId: 'mp-hyperglide',
    sourceName: 'Hyperglide',
    name: 'Hyperglide',
    routeUrl: 'https://www.mountainproject.com/route/107074342/hyperglide',
    grade: 'V5',
    fontGrade: '6C',
    gradeValue: 5,
  },
  {
    id: 'monkey-left',
    sourceId: 'mp-route-114126051',
    sourceName: 'Left',
    name: 'Left',
    routeUrl: 'https://www.mountainproject.com/route/114126051/left',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
  },
  {
    id: 'monkey-left-left',
    sourceId: 'mp-route-114126042',
    sourceName: 'Left Left',
    name: 'Left Left',
    routeUrl: 'https://www.mountainproject.com/route/114126042/left-left',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
  },
  {
    id: 'monkey-bar-direct',
    sourceId: 'mp-monkey-direct',
    sourceName: 'Monkey Bar Direct',
    name: 'Monkey Bar Direct',
    routeUrl:
      'https://www.mountainproject.com/route/107378329/monkey-bar-direct',
    grade: 'V8',
    fontGrade: '7B',
    gradeValue: 8,
  },
  {
    id: 'monkey-monkey-bar-direct-right',
    sourceId: 'mp-route-112381021',
    sourceName: 'Monkey Bar Direct Right',
    name: 'Monkey Bar Direct Right',
    routeUrl:
      'https://www.mountainproject.com/route/112381021/monkey-bar-direct-right',
    grade: 'V9',
    fontGrade: '7C',
    gradeValue: 9,
  },
  {
    id: 'monkey-bar-right',
    sourceId: 'mp-monkey-right',
    sourceName: 'Monkey Bar Right',
    name: 'Monkey Bar Right',
    routeUrl:
      'https://www.mountainproject.com/route/106683440/monkey-bar-right',
    grade: 'V6',
    fontGrade: '7A',
    gradeValue: 6,
  },
  {
    id: 'monkey-monkey-bar-traverse',
    sourceId: 'mp-route-105937677',
    sourceName: 'Monkey Bar Traverse',
    name: 'Monkey Bar Traverse',
    routeUrl:
      'https://www.mountainproject.com/route/105937677/monkey-bar-traverse',
    grade: 'V6',
    fontGrade: '7A',
    gradeValue: 6,
  },
  {
    id: 'monkey-bars',
    sourceId: 'mp-monkey-bars',
    sourceName: 'Monkey Bars',
    name: 'Monkey Bars',
    routeUrl: 'https://www.mountainproject.com/route/106657521/monkey-bars',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
  },
  {
    id: 'monkey-monkey-crack',
    sourceId: 'mp-route-107849034',
    sourceName: 'Monkey Crack',
    name: 'Monkey Crack',
    routeUrl: 'https://www.mountainproject.com/route/107849034/monkey-crack',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
  },
  {
    id: 'monkey-monkey-far',
    sourceId: 'mp-route-121826536',
    sourceName: 'Monkey Far',
    name: 'Monkey Far',
    routeUrl: 'https://www.mountainproject.com/route/121826536/monkey-far',
    grade: 'V9-10',
    fontGrade: '7C+',
    gradeValue: 9,
    gradeMaxValue: 10,
  },
  {
    id: 'monkey-monkey-near',
    sourceId: 'mp-route-126614999',
    sourceName: 'Monkey Near',
    name: 'Monkey Near',
    routeUrl: 'https://www.mountainproject.com/route/126614999/monkey-near',
    grade: 'V5',
    fontGrade: '6C',
    gradeValue: 5,
  },
  {
    id: 'monkey-monkeys-uncle',
    sourceId: 'mp-route-123281460',
    sourceName: "Monkey's Uncle",
    name: "Monkey's Uncle",
    routeUrl: 'https://www.mountainproject.com/route/123281460/monkeys-uncle',
    grade: 'V8',
    fontGrade: '7B',
    gradeValue: 8,
  },
  {
    id: 'monkey-northeast-left',
    sourceId: 'mp-monkey-ne',
    sourceName: 'Northeast Face Left',
    name: 'Northeast Face Left',
    routeUrl:
      'https://www.mountainproject.com/route/113880181/northeast-face-left',
    grade: 'V3',
    fontGrade: '6A',
    gradeValue: 3,
  },
  {
    id: 'monkey-peter-north-pump',
    sourceId: 'mp-route-116621137',
    sourceName: 'Peter North Pump',
    name: 'Peter North Pump',
    routeUrl:
      'https://www.mountainproject.com/route/116621137/peter-north-pump',
    grade: 'V9',
    fontGrade: '7C',
    gradeValue: 9,
  },
  {
    id: 'monkey-pockets',
    sourceId: 'mp-route-113880208',
    sourceName: 'Pockets',
    name: 'Pockets',
    routeUrl: 'https://www.mountainproject.com/route/113880208/pockets',
    grade: 'V2+',
    fontGrade: '5+',
    gradeValue: 2,
  },
  {
    id: 'monkey-prow-direct',
    sourceId: 'mp-route-202093496',
    sourceName: 'Prow Direct',
    name: 'Prow Direct',
    routeUrl: 'https://www.mountainproject.com/route/202093496/prow-direct',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
  },
  {
    id: 'monkey-the-redirect',
    sourceId: 'mp-route-117939655',
    sourceName: 'Redirect, The',
    name: 'Redirect, The',
    routeUrl: 'https://www.mountainproject.com/route/117939655/the-redirect',
    grade: 'V12',
    fontGrade: '8A+',
    gradeValue: 12,
  },
  {
    id: 'monkey-right-of-crack',
    sourceId: 'mp-route-108731202',
    sourceName: 'Right of Crack',
    name: 'Right of Crack',
    routeUrl: 'https://www.mountainproject.com/route/108731202/right-of-crack',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
  },
  {
    id: 'monkey-the-rising-sun',
    sourceId: 'mp-route-123510628',
    sourceName: 'Rising Sun, The',
    name: 'Rising Sun, The',
    routeUrl: 'https://www.mountainproject.com/route/123510628/the-rising-sun',
    grade: 'V2-3',
    fontGrade: '5+',
    gradeValue: 2,
    gradeMaxValue: 3,
  },
  {
    id: 'monkey-seam',
    sourceId: 'mp-route-121742287',
    sourceName: 'Seam',
    name: 'Seam',
    routeUrl: 'https://www.mountainproject.com/route/121742287/seam',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
  },
  {
    id: 'monkey-umpa-lumpa',
    sourceId: 'mp-route-108551582',
    sourceName: 'Umpa Lumpa',
    name: 'Umpa Lumpa',
    routeUrl: 'https://www.mountainproject.com/route/108551582/umpa-lumpa',
    grade: 'V5',
    fontGrade: '6C',
    gradeValue: 5,
  },
]
