import type { CatalogRoute } from './catalog-records'

export const pearlCatalog: CatalogRoute[] = [
  {
    id: 'pearl-across-the-choss',
    sourceId: 'mp-route-107030493',
    sourceName: 'Across the Choss',
    name: 'Across the Choss',
    routeUrl:
      'https://www.mountainproject.com/route/107030493/across-the-choss',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
  },
  {
    id: 'pearl-clam-bumper-right',
    sourceId: 'mp-route-116980157',
    sourceName: 'Clam Bumper Right',
    name: 'Clam Bumper Right',
    routeUrl:
      'https://www.mountainproject.com/route/116980157/clam-bumper-right',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
  },
  {
    id: 'pearl-the-clam-bumper',
    sourceId: 'mp-route-106652005',
    sourceName: 'Clam Bumper, The',
    name: 'Clam Bumper, The',
    routeUrl: 'https://www.mountainproject.com/route/106652005/the-clam-bumper',
    grade: 'V3',
    fontGrade: '6A',
    gradeValue: 3,
  },
  {
    id: 'jennas-jewelry',
    sourceId: 'mp-jennas',
    sourceName: "Jenna's Jewelry",
    name: "Jenna's Jewelry",
    routeUrl: 'https://www.mountainproject.com/route/106652010/jennas-jewelry',
    grade: 'V3-4',
    fontGrade: '6A+',
    gradeValue: 3,
    gradeMaxValue: 4,
  },
  {
    id: 'pearl-northeast-corner',
    sourceId: 'mp-route-202867946',
    sourceName: 'Northeast Corner',
    name: 'Northeast Corner',
    routeUrl:
      'https://www.mountainproject.com/route/202867946/northeast-corner',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
  },
  {
    id: 'northeast-face-center',
    sourceId: 'mp-pearl-ne',
    sourceName: 'Northeast Face Center',
    name: 'Northeast Face Center',
    routeUrl:
      'https://www.mountainproject.com/route/110224533/northeast-face-center',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
  },
  {
    id: 'pearl-pearl-necklace',
    sourceId: 'mp-route-107444907',
    sourceName: 'Pearl Necklace',
    name: 'Pearl Necklace',
    routeUrl: 'https://www.mountainproject.com/route/107444907/pearl-necklace',
    grade: 'V6-',
    fontGrade: '7A',
    gradeValue: 6,
  },
  {
    id: 'the-pearl',
    sourceId: 'mp-pearl-route',
    sourceName: 'Pearl, The',
    name: 'Pearl, The',
    routeUrl: 'https://www.mountainproject.com/route/106056281/the-pearl',
    grade: 'V5',
    fontGrade: '6C',
    gradeValue: 5,
  },
  {
    id: 'six-pack',
    sourceId: 'mp-six-pack',
    sourceName: 'Six Pack',
    name: 'Six Pack',
    routeUrl: 'https://www.mountainproject.com/route/107030486/six-pack',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
  },
  {
    id: 'pearl-the-spreader',
    sourceId: 'mp-route-110224675',
    sourceName: 'Spreader, The',
    name: 'Spreader, The',
    routeUrl: 'https://www.mountainproject.com/route/110224675/the-spreader',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
  },
  {
    id: 'pearl-vajazzled',
    sourceId: 'mp-route-126854254',
    sourceName: 'Vajazzled',
    name: 'Vajazzled',
    routeUrl: 'https://www.mountainproject.com/route/126854254/vajazzled',
    grade: 'V4-5',
    fontGrade: '6B+',
    gradeValue: 4,
    gradeMaxValue: 5,
  },
]
