import type { CatalogRoute } from './catalog-records'

export const splitCatalog: CatalogRoute[] = [
  {
    id: 'front-side-crack',
    sourceId: 'mp-front-crack',
    sourceName: 'Front Side Crack',
    name: 'Front Side Crack',
    routeUrl:
      'https://www.mountainproject.com/route/106617793/front-side-crack',
    grade: 'V0',
    fontGrade: '4',
    gradeValue: 0,
    risk: 'R',
    ydsGrade: '5.8',
  },
  {
    id: 'split-leaning-wide-crack',
    sourceId: 'mp-route-106629920',
    sourceName: 'Leaning Wide Crack',
    name: 'Leaning Wide Crack',
    routeUrl:
      'https://www.mountainproject.com/route/106629920/leaning-wide-crack',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
    ydsGrade: '5.9',
  },
  {
    id: 'split-the-mole',
    sourceId: 'mp-route-116385877',
    sourceName: 'Mole, The',
    name: 'Mole, The',
    routeUrl: 'https://www.mountainproject.com/route/116385877/the-mole',
    grade: 'V7',
    fontGrade: '7A+',
    gradeValue: 7,
  },
  {
    id: 'split-phazed-aka-the-hole',
    sourceId: 'mp-route-107974947',
    sourceName: 'Phazed (a.k.a. The Hole)',
    name: 'Phazed (a.k.a. The Hole)',
    routeUrl:
      'https://www.mountainproject.com/route/107974947/phazed-aka-the-hole',
    grade: 'V10-11',
    fontGrade: '8A',
    gradeValue: 10,
    gradeMaxValue: 11,
  },
  {
    id: 'plumbers-crack',
    sourceId: 'mp-plumbers',
    sourceName: "Plumber's Crack",
    name: "Plumber's Crack",
    routeUrl: 'https://www.mountainproject.com/route/107185645/plumbers-crack',
    grade: 'V2',
    fontGrade: '5+',
    gradeValue: 2,
    risk: 'R',
    ydsGrade: '5.9',
  },
  {
    id: 'split-plumbers-crack-traverse',
    sourceId: 'mp-route-123599243',
    sourceName: 'Plumber’s Crack Traverse',
    name: 'Plumber’s Crack Traverse',
    routeUrl:
      'https://www.mountainproject.com/route/123599243/plumbers-crack-traverse',
    grade: 'V10',
    fontGrade: '7C+',
    gradeValue: 10,
  },
  {
    id: 'split-slice-n-dice',
    sourceId: 'mp-route-107974932',
    sourceName: 'Slice N Dice',
    name: 'Slice N Dice',
    routeUrl: 'https://www.mountainproject.com/route/107974932/slice-n-dice',
    grade: 'V9',
    fontGrade: '7C',
    gradeValue: 9,
    risk: 'R',
  },
  {
    id: 'split-decision',
    sourceId: 'mp-split-decision',
    sourceName: 'Split Decision',
    name: 'Split Decision',
    routeUrl: 'https://www.mountainproject.com/route/110174865/split-decision',
    grade: 'V1',
    fontGrade: '5',
    gradeValue: 1,
  },
  {
    id: 'split-split-decision-sit',
    sourceId: 'mp-route-115968255',
    sourceName: 'Split Decision Sit',
    name: 'Split Decision Sit',
    routeUrl:
      'https://www.mountainproject.com/route/115968255/split-decision-sit',
    grade: 'V5',
    fontGrade: '6C',
    gradeValue: 5,
    risk: 'R',
  },
]
