export const covers = [
  {
    src: '/club-covers/lead-climbing.jpg',
    posMobile: '50% 35%',
    posDesktop: '45% 40%',
    originMobile: '50% 35%',
    originDesktop: '45% 40%',
    scaleMobile: 1.08,
    scaleDesktop: 1.05,
  },
  {
    src: '/club-covers/club-hike.jpg',
    posMobile: '40% 45%',
    posDesktop: '45% 50%',
    originMobile: '40% 45%',
    originDesktop: '45% 50%',
    scaleMobile: 1.1,
    scaleDesktop: 1.06,
  },
  {
    src: '/club-covers/bouldering.jpg',
    posMobile: '40% 35%',
    posDesktop: '45% 40%',
    originMobile: '40% 35%',
    originDesktop: '45% 40%',
    scaleMobile: 1.12,
    scaleDesktop: 1.08,
  },
  {
    src: '/club-covers/dax-climbing-pose.jpg',
    posMobile: '48% 35%',
    posDesktop: '50% 40%',
    originMobile: '48% 35%',
    originDesktop: '50% 40%',
    scaleMobile: 1.1,
    scaleDesktop: 1.06,
  },
  {
    src: '/club-covers/multi-pitch.jpg',
    posMobile: '20% 90%',
    posDesktop: '20% 50%',
    originMobile: '20% 90%',
    originDesktop: '20% 50%',
    scaleMobile: 1.3,
    scaleDesktop: 1.12,
  },
  {
    src: '/club-covers/hoawen-leading-a-crack.jpg',
    posMobile: '70% 45%',
    posDesktop: '55% 45%',
    originMobile: '70% 45%',
    originDesktop: '55% 45%',
    scaleMobile: 1.1,
    scaleDesktop: 1.06,
  },
]
